[project]
name = "terminal-tree"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "click>=8.1.7",
    "textual>=0.79.1",
]

[tool.uv.sources]
textual = { path = "../textual", editable = true }
