[project]
name = "terminal-tree"
version = "0.1.3"
description = "Experimental file navigator for the terminal"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [    
    "textual>=0.85.1",
    "rich>=13.9.4"
]

[project.scripts]
terminal-tree = "tree:run"
